#version: '3.7'

secrets:
  RABBITMQ_DEFAULT_USER:
    external: true
  RABBITMQ_DEFAULT_PASS:
    external: true

  AUTH_PG_HOST:
    external: true
  AUTH_PG_PORT:
    external: true
  AUTH_PG_DATABASE:
    external: true
  AUTH_PG_USER:
    external: true
  AUTH_PG_PW:
    external: true
  POSTGRES_DB:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true

  AUTH_SPRING_USERNAME:
    external: true
  AUTH_SPRING_PASSWORD:
    external: true
  AUTH_PLATFORM_CODE:
    external: true
  AUTH_LINK_CODE:
    external: true
  AUTH_PW_CODE:
    external: true
  AUTH_DATABASE_DRIVER:
    external: true
  AUTH_DATABASE_PLATFORM:
    external: true

  AUTH_MQ_QUEUE:
    external: true
  AUTH_MQ_TOPIC:
    external: true
  AUTH_MQ_VIRTUAL_HOST:
    external: true
  AUTH_MQ_HOST:
    external: true
  AUTH_MQ_USERNAME:
    external: true
  AUTH_MQ_PASSWORD:
    external: true

  MQ_QUEUE:
    external: true
  MQ_TOPIC:
    external: true
  MQ_VIRTUAL_HOST:
    external: true
  MQ_HOST:
    external: true
  MQ_USERNAME:
    external: true
  MQ_PASSWORD:
    external: true
services:
  rabbitmq-ms:
    image: rabbitmq:management
    environment:
      ENV: 'ENV'
    ports:
      - "5672:5672"
      - "15672:15672"
    secrets:
      - MQ_QUEUE
      - MQ_TOPIC
      - MQ_VIRTUAL_HOST
      - MQ_HOST
      - MQ_USERNAME
      - MQ_PASSWORD
  auth-db-ms:
    build:
      context: ./
      dockerfile: ./Dockerfile.pg.dev
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    #    volumes:
    #      - auth-db:/var/lib/postgresql/data
    secrets:
      - AUTH_PG_HOST
      - AUTH_PG_PORT
      - AUTH_PG_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  auth-api-ms:
    image: eclipse-temurin:17-jdk-alpine
    build:
      context: ./
      dockerfile: ./Dockerfile.sb.dev
    depends_on: [auth-db-ms, rabbitmq-ms]
    ports:
      - '443:443'
    environment:
      SERVER_PORT: 443
      LOCS_PORT: 443
    secrets:
      - AUTH_PG_HOST
      - AUTH_PG_PORT
      - AUTH_PG_DATABASE
      - AUTH_PG_USER
      - AUTH_PG_PW

      - AUTH_SPRING_USERNAME
      - AUTH_SPRING_PASSWORD
      - AUTH_PLATFORM_CODE
      - AUTH_LINK_CODE
      - AUTH_PW_CODE
      - AUTH_DATABASE_DRIVER
      - AUTH_DATABASE_PLATFORM

      - AUTH_MQ_QUEUE
      - AUTH_MQ_TOPIC
      - AUTH_MQ_VIRTUAL_HOST
      - AUTH_MQ_HOST
      - AUTH_MQ_USERNAME
      - AUTH_MQ_PASSWORD

